name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run:
    strategy:
      matrix:
        operating-system: [ubuntu-latest, macos-latest]
        php-versions: ['7.4']
    runs-on: ${{ matrix.operating-system }}

    name: Tests for PHP ${{ matrix.php-versions }} on ${{ matrix.operating-system }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run Psalm
        run: composer run-script psalm

      - name: Run Codeception Integration Tests
        run: composer run-script codecept


